### ISSUE TITLE
Differences from "KeepOn" ?

### ISSUE THREAD

**Issue by karam72** [Alberto97/AlwaysOnDisplayToggle#2]
Hi,

Thanks your for contributions... I am curious only: Is there any main difference from this project: https://github.com/twentynine78/KeepOn 

Thank you

**Comment by Alberto97** [comment]
Hi, yes this is a completely different thing.
This is just a tile that toggles the [Always on Display feature](https://en.wikipedia.org/wiki/Always_on_Display) which shows time and notifications when the device is locked (basically it is Ambient Display with the only difference that the screen never turns off) and is typically available on devices with AMOLED/OLED displays.
KeepOn instead prevents the device from being locked in the fist place.

**Comment by karam72** [comment]
Thank you :)
